version: '3.7'

services:
  mysql_sae51:
    image: mysql:8
    ports:
      - '3306:3306'
    security_opt:
    - seccomp:unconfined
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPWD}
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './conf_mysql.sql:/docker-entrypoint-initdb.d/dump.sql'
    networks:
      sae_network:
        ipv4_address: 172.36.30.2

  dbml:
    build:
      context: .
      dockerfile: dbml/Dockerfile.ubuntu
    volumes:
      - "./dump.png:/root/dump.png"
    networks:
      sae_network:
        ipv4_address: 172.36.30.3

  wg-easy_sae_51:
    environment:
      - WG_HOST=${WIRGURL}
      - PASSWORD=${WIRGPWD}
      - WG_DEFAULT_DNS=8.8.8.8
    image: weejewel/wg-easy
    container_name: wg-easy_sae_51
    volumes:
      - 'wireguard_data_sae51:/etc/wireguard'
    ports:
      - "51822:51820/udp"
      - "51823:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      sae_network:
        ipv4_address: 172.36.30.4

volumes:
  mysql_data:
  wireguard_data_sae51:

networks:
  sae_network:
    name: sae_network_51
    external: false
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.36.0.0/16